### PR TITLE
BIP32 HD key generation

### PR DESCRIPTION
**Pull request by Strangework**
Added BIP32 HD key generation, modified tests to confirm generated HD keys against those in vectors.json

### CODE REVIEW

**Comment by prusnak** [comment]
Drop the base58 dependency and copy the function `b58encode` to the code.

**Comment by Strangework** [comment]
I've removed the base58 dependency and copied over b58encode (with some refactoring so all the logic is contained within that function)

**Comment by prusnak** [comment]
Please fix the build failures: https://travis-ci.org/trezor/python-mnemonic/builds/495817463

**Comment by Strangework** [comment]
All builds pass now - I encountered a separate issue on my own machine with Python 2.7 where vectors.json would be opened expecting an ascii encoding. I modified Mnemonic's initializer to account for this.

**Comment by prusnak** [comment]
Merged via https://github.com/trezor/python-mnemonic/commit/c78bdbe6ac0a855b048dcbf13ef79e5145b6181c

**Pull request closed without merging**
