### PR TITLE
Obsoletes #23. Fix #22. Add `to_entropy` method to reverse entropy data from mnemonic word list. ...

### LINKED ISSUE #22: Feature request: provide method to reverse engineer entropy from mnemonic
This *may* be a duplicate of #18, but there's no equivalent to [this method](https://github.com/bitcoinj/bitcoinj/blob/6aa4e51de6004f7171802bbce9c1660228d05aae/core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java#L147), which enables reverse engineering the original entropy from the word list.

### PR DESCRIPTION
**Pull request by posita**
... Include new unit test.

This PR includes minor code fixes, such as converting tabs -> spaces in `mnemonic.py` (per [PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces)) and making the `Exception`s raised more specific to the types of errors encountered in various places. These changes have each been broken out in their own respective commits.

**WARNING**: this is pretty much a verbatim translation from [this Java implementation](https://github.com/bitcoinj/bitcoinj/blob/6aa4e51de6004f7171802bbce9c1660228d05aae/core/src/main/java/org/bitcoinj/crypto/MnemonicCode.java#L147). While technically correct, there might be *much* more efficient ways of doing this in python. I have not spent any time optimizing.

Now one can do something like this to pull out the original entropy:

```python
>>> m = Mnemonic('english')
>>> w = m.to_mnemonic("She sells sea shells down by the sea shore?!")
>>> w
'fat drip elite traffic fine curtain smart attack grace animal broom speak fine curtain smart arrive hunt rocket marine shaft must demand pave piano inflict climb elite traffic manage rice neutral tomorrow entry'
>>> m.to_entropy(w.split())
bytearray(b'She sells sea shells down by the sea shore?!')
```

### CODE REVIEW

**Comment by posita** [comment]
@prusnak: does this satisfy your request from this https://github.com/trezor/python-mnemonic/pull/23#issuecomment-77604869?

**Comment by posita** [comment]
> @prusnak: does this satisfy your request from this #23 (comment)?

Sorry to nag. Is there any chance on getting this merged?

**Comment by prusnak** [comment]
Sorry. I overlooked your comment from April. Merged in.

**Comment by posita** [comment]
Thanks!

**Pull request merged**
