### PR TITLE
Use sys.version_info to check python version, not sys.version

### PR DESCRIPTION
**Pull request by hukkinj1**
See Python docs https://docs.python.org/3/library/sys.html#sys.version
> ...Do not extract version information out of it (`sys.version`), rather, use version_info...

### CODE REVIEW

**Comment by hukkinj1** [comment]
BTW, how would you feel about a PR that removes Python 2 and Python 3.4 support entirely, since both have reached their end of life?

**Comment by matejcik** [comment]
> BTW, how would you feel about a PR that removes Python 2 and Python 3.4 support entirely, since both have reached their end of life?

A PR would be welcome.

**Comment by matejcik** [comment]
if you want to do it, please close this PR as it seems that it would be pointless?

**Comment by hukkinj1** [comment]
:+1: Made the other PR here https://github.com/trezor/python-mnemonic/pull/71/

Closing this one.

**Pull request closed without merging**
